name: Github Actions Demo

on:
    push:
        branches:
            - main
    pull_request: 
        branches: 
            - main

env:
    MY_HOST: '127.0.0.1'

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "buildjob Re ${{ github.actor }}"

    test-job:
        runs-on: ubuntu-latest
        needs: build-job
        steps:
            - run: echo "test -job  ${{ github.repository }}"

    deploy-job:
        runs-on: ubuntu-latest
        needs: test-job
        steps:
            - run: echo "need deploy - job to production server  ${{ job.status }}"
            - run: echo "need deploy - job to production server  ${{ env.MY_HOST }}"